blank_issues_enabled: false
contact_links:
  - name: "Support tickets"
    url: https://www.odoo.com/help
    about: "Please favour opening an official ticket if you have an active subscription."
  - name: "Code contribution"
    url: https://www.odoo.com/documentation/latest/contributing/development.html#make-your-first-contribution
    about: "If you have an idea of the change to apply in the codebase, please open a pull request to speed up the process."
  - name: "Translation Change"
    url: https://explore.transifex.com/odoo/
    about: Please use the Transifex tool for Translations (see https://github.com/odoo/odoo/wiki/Translations for more information).
  - name: "Odoo Help Forums"
    url: https://www.odoo.com/forum/help-1
    about: "Please ask and answer questions about custom code, functional aspects or any Odoo-related topic here."
  - name: "Documentation Feedback"
    url: https://github.com/odoo/documentation/issue
    about: "If your feedback is about the documentation, please post your issue in the dedicated repository."
  - name: "Security Related Question"
    url: https://www.odoo.com/security-report
    about: "Read our Responsible Disclosure page and contact the Security Team."

